services:
  employee:
    build: ./employee
    ports:
      - "5000:5000"
    environment:
      TEST_MODE: "true"
      BROWSER: chrome
      HEADLESS: "true"
      DATABASE_PATH: /app/expense_manager.db
      TEST_DATABASE_PATH: /app/tests/test_db/test_expense_manager.db
